# Generated by Django 6.1 on 2026-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_unique_student_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('package', models.FloatField(default=0.0)),
            ],
        ),
    ]
