# Generated by Django 6.1 on 2026-08-27 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_placement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='role',
            new_name='job_role',
        ),
        migrations.AddField(
            model_name='placement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placement',
            name='placement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='package',
            field=models.CharField(max_length=50),
        ),
    ]
